application: edwinportfolio-1282 
version: 1
runtime: go
api_version: go1
threadsafe: true

handlers:
- url: /
  static_files: static/index.html
  upload: static/index.html

- url: /
  static_dir: static